apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mapserver

bases:
  - ../../base

resources:
  - ingress.yaml

configMapGenerator:
  - name: mapfile-config
    namespace: mapserver
    files:
      - "mapfile.map"
