version: '3.3'

services:
  mapserver:
    # image: mcerolini/mapserver:${MAPSERVER_VERSION}
    build:
      context: .
      args:
        GDAL_VERSION: ${GDAL_VERSION}
        MAPSERVER_VERSION: ${MAPSERVER_VERSION}
    ports: 
      - "8000:80"
    volumes: 
      - ./mapfiles:/usr/src/mapfiles/
