version: '2.1'

services:

  mapserver:
    build:
      context: .
      args:
        GDAL_VERSION: ${GDAL_VERSION}
        MAPSERVER_VERSION: ${MAPSERVER_VERSION}
    image: mcerolini/mapserver:${MAPSERVER_VERSION}

