# Access:
# kubectl proxy
# http://localhost:8001/api/v1/namespaces/mapserver/services/http:mapserver-service:/proxy/

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mapserver

bases:
  - ../../base

configMapGenerator:
  - name: mapfile-config
    namespace: mapserver
    files:
      - "mapfile.map"
